### ISSUE TITLE
Can u help me How to complie libimobiledevice?

### ISSUE THREAD

**Issue by 1714146** [rcmpayne/libimobiledevice-Compiled-Windows#4]
Can u help me How to compile libimobiledevice? thanks u!

**Comment by rcmpayne** [comment]
Sure, let me add some steps for you in the next few days. also have a new upload of compiled apps with msys2 64bit.

**Comment by 1714146** [comment]
Thank you very much!

**Comment by 1714146** [comment]
When i run idevicebackup2 backup --full c:\temp -d . igot list error message!

21:52:04 src\property_list_service.c:127 internal_plist_send(): sending 146 bytes
21:52:04 src\service.c:140 service_send(): sending 4 bytes
21:52:04 src\service.c:140 service_send(): sending 146 bytes
21:52:04 src\property_list_service.c:132 internal_plist_send(): sent 146 bytes
21:52:04 src\property_list_service.c:133 internal_plist_send(): printing 409 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<string>DLMessageProcessMessage</string>
	<dict>
		<key>SupportedProtocolVersions</key>
		<array>
			<real>2.000000</real>
			<real>2.100000</real>
		</array>
		<key>MessageName</key>
		<string>Hello</string>
	</dict>
</array>
</plist>
21:52:04 src\property_list_service.c:191 internal_plist_receive_timeout(): initial read=4
21:52:04 src\property_list_service.c:200 internal_plist_receive_timeout(): 176 bytes following
21:52:04 src\property_list_service.c:213 internal_plist_receive_timeout(): received 176 bytes
21:52:04 src\property_list_service.c:239 internal_plist_receive_timeout(): printing 434 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<string>DLMessageProcessMessage</string>
	<dict>
		<key>ErrorCode</key>
		<integer>1</integer>
		<key>ErrorDescription</key>
		<string>No common supported protocol version</string>
		<key>MessageName</key>
		<string>Response</string>
	</dict>
</array>
</plist>
Could not perform backup protocol version exchange, error code -6


Can u help me to solve this error ? thank u!
